fix: concurrent solvers
defuse-is-near/defuse-contracts pull request #9
Opened 2024-07-01 16:09 UTC by gonchar1987

2024-07-01 16:18 UTC, fusede requested changes

2024-07-01 16:18 UTC, fusede commented on contracts/src/intent/error.rs
> +    #[error("Base64: {0}")]
Hm, is there a convention for error messages in NEAR?
According to Rust guidelines, `Display` implementations for error messages [should](https://github.com/rust-lang/api-guidelines/blob/master/src/interoperability.md#error-types-are-meaningful-and-well-behaved-c-good-err) start with lowercase letter, so they can be then combined chained together in a more nice format

2024-07-01 16:18 UTC, fusede commented on intent/src/lib.rs
> +            },
```suggestion
            Ok(Some(_)) => self.execute_intent(id, amount).unwrap(),
```

2024-07-02 09:24 UTC, mitinarseny approved these changes

2024-07-02 09:26 UTC, fusede approved these changes

2024-07-02 09:29 UTC, merged